[package]
name = "stamp-core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <andrew@killtheradio.net>"]
edition = "2018"

[dependencies]
base64 = "0.13"
chacha20poly1305 = "0.9"
chrono = { version = "0.4", features = ["serde"] }
getset = "0.1"
hmac = "0.12"
getrandom = "0.2"
rmp-serde = "0.15"
serde = "1.0"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_yaml = "0.8"
sha2 = "0.10"
sodiumoxide = "0.2.6"
thiserror = "1.0"
url = { version = "2.2", features = ["serde"] }
xsalsa20poly1305 = "0.8"

[dev-dependencies]
rmpv = { version = "0.4", features = ["serde"] }

