#brace_style = "SameLineWhere"
#condense_wildcard_suffixes = true
#control_brace_style = "AlwaysSameLine"
#enum_discrim_align_threshold = 0
fn_call_width = 100
fn_params_layout = "Tall"
#format_macro_matchers = true
#group_imports = "Preserve"
hard_tabs = false
#imports_granularity = "Preserve"
#imports_layout = "Mixed"
#indent_style = "Block"
match_block_trailing_comma = false
max_width = 140
merge_derives = true
reorder_imports = true
reorder_modules = true
#space_after_colon = true
#space_before_colon = false
#spaces_around_ranges = false
#struct_field_align_threshold = 0
#struct_lit_single_line = true
tab_spaces = 4
#trailing_comma = "Vertical"
#trailing_semicolon = true
#type_punctuation_density = "Wide"
use_try_shorthand = true
#where_single_line = false
